### ISSUE TITLE
jrafsantos_whitelist

### ISSUE THREAD

**Issue by jrafsantos** [cjkoepke/ada-safeguard#1]
https://pooltool.io/
https://cardanoassets.com/
https://adapools.org/
https://adastat.net/
https://cardanoscan.io/
https://forum.cardano.org/
https://iohk.io/
https://blockfrost.io/
https://medium.com/liqwid-finance-introduction-series
https://adapulse.io/
https://www.adatainment.com/
https://adaex.org/
https://pool.pm/
https://cardanians.io/en
https://spacebudz.io/
https://www.abitcoin.io/
https://www.cardanokidz.com/
https://cardano.ideascale.com/

**Comment by cjkoepke** [comment]
Thanks!
